version: "3.8"
services: 
    amd64:
        build: 
            context: .
            dockerfile: Dockerfile_amd64
        volumes: 
            - ./src:/php-src/ext/src:delegated
        tty: true
        privileged: true
        cap_add: 
            - "SYS_PTRACE"
        security_opt: 
            - seccomp:unconfined
    i386:
        build:
            context: .
            dockerfile: Dockerfile_i386
        volumes: 
            - ./src:/php-src/ext/src:delegated
        tty: true
        privileged: true
        cap_add: 
            - "SYS_PTRACE"
        security_opt: 
            - seccomp:unconfined
